//------------------------------------------------------------------------------ 
// <auto-generated> 
// This code was generated by a tool. 
// 
// Changes to this file may cause incorrect behavior and will be lost if 
// the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------

using Bas.RedYarn.WebApp.ViewModels;
using System;
using System.Threading.Tasks;

namespace Bas.RedYarn.WebApp.Services
{
    public interface IDataService
    {
		Task<DiagramViewModel> GetDiagramViewModelAsync(Guid id);
        Task<DiagramViewModel> CreateDiagramViewModelAsync(DiagramViewModel diagramViewModel);
        Task<DiagramViewModel> UpdateDiagramViewModelAsync(Guid id, DiagramViewModel diagramViewModel);
        Task DeleteDiagramViewModelAsync(Guid id);

		Task<CharacterViewModel> GetCharacterViewModelAsync(Guid id);
        Task<CharacterViewModel> CreateCharacterViewModelAsync(CharacterViewModel characterViewModel);
        Task<CharacterViewModel> UpdateCharacterViewModelAsync(Guid id, CharacterViewModel characterViewModel);
        Task DeleteCharacterViewModelAsync(Guid id);

		Task<StorylineViewModel> GetStorylineViewModelAsync(Guid id);
        Task<StorylineViewModel> CreateStorylineViewModelAsync(StorylineViewModel storylineViewModel);
        Task<StorylineViewModel> UpdateStorylineViewModelAsync(Guid id, StorylineViewModel storylineViewModel);
        Task DeleteStorylineViewModelAsync(Guid id);

		Task<AuthorViewModel> GetAuthorViewModelAsync(Guid id);
        Task<AuthorViewModel> CreateAuthorViewModelAsync(AuthorViewModel authorViewModel);
        Task<AuthorViewModel> UpdateAuthorViewModelAsync(Guid id, AuthorViewModel authorViewModel);
        Task DeleteAuthorViewModelAsync(Guid id);
	}
}